In [6]:
import numpy as np
mylist=[1,2,3]
arr=np.array(mylist)

In [7]:
mylist=[1,2,3]

In [8]:
type(mylist)

list

In [10]:
arr=np.array(mylist)

In [12]:
type(arr)

numpy.ndarray

In [13]:
print("eee")

eee


In [14]:
print(arr)

[1 2 3]


In [15]:
arr

array([1, 2, 3])

In [16]:
np.arange(10,100,20)

array([10, 30, 50, 70, 90])

In [67]:
np.ones((3,5),int)*10

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [63]:
np.random.seed(101)
arr=np.random.randint(20,100,5)


In [64]:
arr

array([31, 90, 83, 95, 29])

In [25]:
arr2=np.random.randint(0,100,10)

In [26]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [28]:
arr2.max()

93

In [30]:
arr.argmin()

7

In [31]:
arr.mean()

60.8

In [33]:
arr.shape


(10,)

In [34]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [41]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [42]:
mat=np.arange(0,100).reshape((10,10))
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [65]:
mat[:,2]


array([ 2, 12,  0,  0,  0,  0, 62, 72, 82, 92])

In [48]:
mat[2:6,2:9]=0

In [49]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21,  0,  0,  0,  0,  0,  0,  0, 29],
       [30, 31,  0,  0,  0,  0,  0,  0,  0, 39],
       [40, 41,  0,  0,  0,  0,  0,  0,  0, 49],
       [50, 51,  0,  0,  0,  0,  0,  0,  0, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [51]:
newmat=mat.copy()

In [54]:
newmat[7:9,0:3]=999

In [58]:
newmat


array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,   0,   0,   0,   0,   0,   0,   0,  29],
       [ 30,  31,   0,   0,   0,   0,   0,   0,   0,  39],
       [ 40,  41,   0,   0,   0,   0,   0,   0,   0,  49],
       [ 50,  51,   0,   0,   0,   0,   0,   0,   0,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [999, 999, 999,  73,  74,  75,  76,  77,  78,  79],
       [999, 999, 999,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [59]:
print("plooo")

plooo


In [ ]:
plt.imshow()